// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiYsnmcna2GrgnSk9RaGd53a6gxSbdaRU',
    appId: '1:393105423189:ios:889d7247eb991af06f8ddc',
    messagingSenderId: '393105423189',
    projectId: 'cross-platform-alarm-app',
    storageBucket: 'cross-platform-alarm-app.firebasestorage.app',
    iosBundleId: 'com.philio.easyClipboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiYsnmcna2GrgnSk9RaGd53a6gxSbdaRU',
    appId: '1:393105423189:ios:889d7247eb991af06f8ddc',
    messagingSenderId: '393105423189',
    projectId: 'cross-platform-alarm-app',
    storageBucket: 'cross-platform-alarm-app.firebasestorage.app',
    iosBundleId: 'com.philio.easyClipboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwf1PtAym07AxQGEv2KXtdr9mWE1zWdpc',
    appId: '1:393105423189:web:886a9bf92ffafad96f8ddc',
    messagingSenderId: '393105423189',
    projectId: 'cross-platform-alarm-app',
    authDomain: 'cross-platform-alarm-app.firebaseapp.com',
    storageBucket: 'cross-platform-alarm-app.firebasestorage.app',
  );
}
